travis:
  secure:
    BINSTAR_TOKEN: ES/CcNWU4NezrZmo9fSAa++ElJoQHRpLQj9DwzHNdMJ+2BQACFObBzdkzZF8471VcH8PFAxUS2K5Ory2Vgfwr73ICBmRK8U3fYAddtzXzAxVY+Obs9BbJBctxg+ffs6AcaXXgyYN5lW9fDltFglQQPfXhSwhkRV8IFawGCJ1fgc1qapQfNjDETr+ymL9w3CL42cGTxevs1X/I/vwwRt1au1nbnz567ZeLL5KzMP85bOfZ9R7fJe/q2ghxUZLkXOHkExwNfYZnWOW77g6L+v0F6oZC2+nfqriNAsbraVvTSHY2pf+qmz6WfRTNIW+oE0HNAU+GUehO0ICvME0rHkElSPlFvN1P5+0gBcoMsd2wFvaHn10w4GjYHDSRmzcHvlHsX2vDmym2PoHTon542SRpUYMbXu0O+kCaobVsWlW8cM2Ouzlx2ccKWI3Bjw3hYaEGJGtGvFSDC4fJBxGvQkgDg0/qyhmYNd5TMN0jAbpPEPvM5s0/Rlb2QJi6vup9xW16msW2/j1ojY59l7bdUhQq1BNlboVIN13UMen1BneQ10UWMgyVi7PDg7EAunWoJ0IOGcK8KBR/VIiRv4u0ewfdXi1FM9hKY6DwYd7F6eRsfHIXG72CR7ELekl1DsAIuC3WdrflsGtOEzNozNSinvUnvAegAyIPjyVc+8NM3AhsXA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
